### ISSUE TITLE
Open with binary flag

### ISSUE THREAD

**Issue by Tigzy** [sqlcipher/sqlcipher-tools#2]
Otherwise the read and write fails.
https://github.com/sqlcipher/sqlcipher-tools/blob/master/decrypt.c#L50

**Comment by sjlombardo** [comment]
I added this to the latest commit bbaf38f. As far as I'm aware though the b flag is ignored (i.e. included only for legacy compatibility purposes) on modern POSIX systems. Out of curiosity, what platform did you run into read/write failures on?

**Comment by Tigzy** [comment]
On Windows, with VS 2010.

**Comment by Tigzy** [comment]
It's reading until the first null byte met, then it sets the feof flag.
