### ISSUE TITLE
Support for hex password?

### ISSUE THREAD

**Issue by protex** [sqlcipher/sqlcipher-tools#3]
I have an sqlcipher encrypted database that I can decrypt successfully using the following:

```
sqlcipher my.db
> PRAGMA key = \"x'<my-hex-password>'\"
> PRAGMA cipher_compatibility = 3
```

I'd like to use this utility to decrypt the file into a plaintext db, but I don't think it supports the hex password? From what I can tell, the file is essentially set up for "cipher_compatibilty = 3", so, I just need to figure out the hex part.

**Comment by sjlombardo** [comment]
Since you already have the sqlcipher command line tool, the easier way to do this is to use the [sqlcipher_export() command](https://www.zetetic.net/sqlcipher/sqlcipher-api/#example-2-decrypt-a-sqlcipher-database-to-a-plaintext-database).
